"""Decision data, independent of controllers and generation strategies."""
from __future__ import annotations
from dataclasses import dataclass
from typing import TYPE_CHECKING
from ...data_structs.decision_option import DecisionOption
from .options import (DeclareAttackersOption, DeclareBlockersOption, MulliganOption,
                      MulliganBottomOption, DiscardOption, AbilityResolutionOption)

if TYPE_CHECKING:
    from .option_space import DecisionOptionSpace
    from .policies import GenerationPolicy
    from ....game_state import State, Player, Card
    from ...data_structs.ability import Ability
    from ...data_structs.game_action import GameAction
    from ....mana.mana_solver import ManaSolverResult
    from ....mana.mana_value import ManaRequirement

@dataclass(frozen=True)
class DecisionRequest[T: DecisionOption]:
    """!
    @brief Base immutable request for a decision option space.
    """
    state: State | None
    player: Player

    @property
    def participants(self) -> tuple[Player, ...]:
        """!
        @brief Return players participating in this request.
        @return Tuple of players in the game.
        """
        if self.state is None:
            raise ValueError("This decision requires a game state.")
        return tuple(self.state.players)

    @property
    def option_type(self) -> type[T]:
        """!
        @brief Return the concrete option type generated by this request.
        @return Decision option type.
        """
        raise NotImplementedError

    def option_space(self, policy: GenerationPolicy | None = None) -> DecisionOptionSpace[T]:
        """!
        @brief Create a lazy option space for this request.
        @param policy Optional generation policy.
        @return Decision option space.
        """
        from .option_space import DecisionOptionSpace
        return DecisionOptionSpace(self, policy)

    @property
    def options(self) -> DecisionOptionSpace[T]:
        """!
        @brief Return the default option space for this request.
        @return Decision option space using the default policy.
        """
        return self.option_space()

@dataclass(frozen=True)
class StateDecisionRequest[T: DecisionOption](DecisionRequest[T]):
    """!
    @brief In-game request that always carries a State; setup requests may not.
    """
    state: State

@dataclass(frozen=True)
class PriorityDecisionRequest(StateDecisionRequest["GameAction"]):
    """!
    @brief Decision request for actions while a player has priority.
    """
    @property
    def option_type(self) -> type[GameAction]:
        """!
        @brief Return the concrete option type generated by this request.
        @return Decision option type.
        """
        from ...data_structs.game_action import GameAction
        return GameAction

@dataclass(frozen=True)
class AbilityDecisionRequest(StateDecisionRequest["GameAction"]):
    """!
    @brief Decision request for generating actions from one ability.
    """
    ability: Ability
    choices: tuple[GameAction, ...] | None = None

    @property
    def option_type(self) -> type[GameAction]:
        """!
        @brief Return the concrete option type generated by this request.
        @return Decision option type.
        """
        from ...data_structs.game_action import GameAction
        return GameAction

@dataclass(frozen=True)
class DeclareAttackersRequest(StateDecisionRequest[DeclareAttackersOption]):
    """!
    @brief Decision request for declaring attackers.
    """
    option_type = DeclareAttackersOption

@dataclass(frozen=True)
class DeclareBlockersRequest(StateDecisionRequest[DeclareBlockersOption]):
    """!
    @brief Decision request for declaring blockers.
    """
    option_type = DeclareBlockersOption

@dataclass(frozen=True)
class MulliganRequest(StateDecisionRequest[MulliganOption]):
    """!
    @brief Decision request for taking or declining a mulligan.
    """
    option_type = MulliganOption
    mulligans_taken: int = 0
    can_mulligan: bool = True

@dataclass(frozen=True)
class MulliganBottomRequest(StateDecisionRequest[MulliganBottomOption]):
    """!
    @brief Decision request for choosing mulligan bottom cards.
    """
    option_type = MulliganBottomOption
    count: int

@dataclass(frozen=True)
class DiscardRequest(StateDecisionRequest[DiscardOption]):
    """!
    @brief Decision request for choosing cards to discard.
    """
    option_type = DiscardOption
    count: int

@dataclass(frozen=True)
class ManaGenerationRequest(StateDecisionRequest["ManaSolverResult"]):
    """!
    @brief Decision request for producing a mana payment plan.
    """
    requirement: ManaRequirement
    reserved: frozenset[Card] = frozenset()

    @property
    def option_type(self) -> type[ManaSolverResult]:
        """!
        @brief Return the concrete option type generated by this request.
        @return Decision option type.
        """
        from ....mana.mana_solver import ManaSolverResult
        return ManaSolverResult

# Names used by earlier versions of the decision-maker interface.
PriorityActionRequest = PriorityDecisionRequest
AbilityRequest = AbilityDecisionRequest
AttackerDeclarationRequest = DeclareAttackersRequest
BlockerDeclarationRequest = DeclareBlockersRequest


@dataclass(frozen=True)
class AbilityResolutionRequest(StateDecisionRequest[AbilityResolutionOption]):
    """!
    @brief Choice made by the affected player while one effect is resolving.
    The resolving effect supplies eligible objects; activation, timing and mana
    checks do not apply a second time. Context identifies the originating ability.
    """
    option_type = AbilityResolutionOption
    context: object
    candidates: tuple
    count: int
    kind: str

__all__ = [
    "DecisionRequest", "StateDecisionRequest", "PriorityDecisionRequest", "AbilityDecisionRequest",
    "DeclareAttackersRequest", "DeclareBlockersRequest", "MulliganRequest",
    "MulliganBottomRequest", "DiscardRequest", "ManaGenerationRequest",
    "AbilityResolutionRequest", "PriorityActionRequest", "AbilityRequest",
    "AttackerDeclarationRequest", "BlockerDeclarationRequest",
]
