"""Playing lands is a special action; intrinsic basic-land mana abilities (CR 305)."""
from game.game_actions.data_structs.ability import ManaAbilityDefinition

from dataclasses import dataclass
from functools import lru_cache
from game.game_actions.data_structs.ability import PlayLandAbilityDefinition

PLAY_LAND_DEFINITION = PlayLandAbilityDefinition()

from game.enums import CardType, CardSubtype, ManaType, TurnPhase, ZoneType
from game.game_actions.data_structs.game_action import (
    GameAction,
    ResolutionContext,
    ScheduledResolution,
    FixedExecutionPlan,
)
from game.game_actions.data_structs.operation import Operation
from game.game_actions.resolution.event_bus import GameEvent

BASIC_LAND_MANA = {
    "PLAINS": ManaType.WHITE,
    "ISLAND": ManaType.BLUE,
    "SWAMP": ManaType.BLACK,
    "MOUNTAIN": ManaType.RED,
    "FOREST": ManaType.GREEN,
}


def land_play_window_error(player, state):
    """Player/timing rules shared by discovery and concrete land validation."""
    if player not in state.players or getattr(player, "has_lost", False):
        return "The player cannot play lands in this game."
    if state.priority.current_player is not player:
        return "You do not have priority."
    if (state.active_player is not player
            or state.turn.phase not in {TurnPhase.PRECOMBAT_MAIN, TurnPhase.POSTCOMBAT_MAIN}
            or not state.stack.is_empty()):
        return "Play a land during your main phase with an empty stack."
    if player.lands_played_this_turn >= player.land_plays_per_turn:
        return "You have used all land plays for this turn."
    return None


def land_play_timing_error(card, player, state):
    """Shared rules independent of which effect grants permission to play a land."""
    error = land_play_window_error(player, state)
    if error:
        return error
    if getattr(card, "_game_state", None) is not state:
        return "The land must belong to this game."
    if CardType.LAND not in card.get_types(state):
        return "This card is not a land."
    if card.get_zone() in {ZoneType.BATTLEFIELD, ZoneType.STACK}:
        return "A land cannot be played from the battlefield or stack."
    return None


def land_play_error(card, player, state, permission=None):
    """Recheck live permissions as well as timing, type and remaining land plays."""
    error = land_play_timing_error(card, player, state)
    if error:
        return error
    permissions = card.get_land_play_ability_defs(state)
    if permission is not None:
        if permissions.get(permission.key) != permission:
            return "The permission to play this land is no longer available."
        return permission.validation_error(card, player, state)
    for definition in permissions.values():
        if definition.validation_error(card, player, state) is None:
            return None
    return "You have no permission to play this land from its current zone."


class PlayLandOperation(Operation):
    """!
    @brief Execute the state change belonging to a land special action.
    """

    def validation_error(self, state):
        """!
        @brief Return a validation message when the requested land play is illegal.

        @param state Current game state.
        @return Validation error message, or `None`.
        """
        if (self.context.source_revision is not None
                and self.context.source.zone_revision != self.context.source_revision):
            return "The land changed zones after this action was chosen."
        return land_play_error(self.context.source, self.context.controller, state, self.context.ability)

    def lki_cards(self, state):
        return (self.context.source,)

    def execute(self, state):
        """!
        @brief Move the land onto the battlefield and consume one land play.

        Validation is repeated immediately before mutation so a previously
        legal land action cannot execute after the game state has changed.

        @param state Current game state.
        @return Events generated by the zone change and land play.
        @throws ValueError If the land play is no longer legal.
        """
        error = self.validation_error(state)
        if error:
            raise ValueError(error)

        from game.operations.card_operations import MoveCardOperation

        player, card = self.context.controller, self.context.source
        from game.game_actions.resolution.replacement_effects import ReplacementResolver
        from game.game_actions.resolution.operation_executor import OperationExecutor
        move = MoveCardOperation(self.context, card, ZoneType.BATTLEFIELD)
        move.entry_controller = player
        events = OperationExecutor().execute_batch(state, ReplacementResolver().replace(state, (move,)))

        player.lands_played_this_turn += 1
        events.append(
            GameEvent("land_played", card, player, {"lands_played": player.lands_played_this_turn})
        )
        return events


@dataclass(frozen=True)
class LandPlayAction(GameAction):
    """!
    @brief Game action representing the special action of playing one land.

    @var card
        Land card to play.
    @var player
        Player performing the special action.
    """

    card: object
    player: object
    permission: PlayLandAbilityDefinition | None = None
    source_revision: int | None = None

    def validation_error(self, state):
        """!
        @brief Return a validation message when this land play is not legal.

        @param state Current game state.
        @return Validation error message, or `None`.
        """
        if self.source_revision is not None and self.card.zone_revision != self.source_revision:
            return "The land changed zones after this action was chosen."
        return land_play_error(self.card, self.player, state, self.permission)

    def get_intents(self):
        """!
        @brief Build the scheduled resolution implementing this land play.

        The action schedules a fixed operation rather than placing an object on
        the stack, preserving the special-action semantics of playing a land.

        @return Tuple containing the land-play resolution.
        """
        context = ResolutionContext(
            controller=self.player, source=self.card, action_key="play_land",
            ability=self.permission, source_revision=self.source_revision,
        )
        return (ScheduledResolution(FixedExecutionPlan([PlayLandOperation(context)]), context),)


@lru_cache(maxsize=6)
def mana_ability(mana):
    """!
    @brief Return the shared intrinsic tap-for-mana ability for one mana type.

    Definitions are immutable and cached so every basic land producing the same
    mana type may reuse the same ability definition.

    @param mana Mana type produced by the ability.
    @return Cached immutable mana-ability definition.
    """
    from game.game_actions.data_structs.ability import AbilityDefinition, SubAbilityDefinition
    from game.game_actions.data_structs.action_node import (
        EffectActionNode,
        ImmutableEffectToSlotMap,
    )
    from game.game_actions.card_effects import TapSourceEffect
    from game.game_actions.mana_effects import AddManaEffect

    tap = TapSourceEffect("tap_for_mana")
    add = AddManaEffect("add_" + mana.name.lower(), mana)

    return ManaAbilityDefinition(
        key="mana_" + mana.name.lower(),


        cost_subdefs=(
            SubAbilityDefinition(
                action_node=EffectActionNode(ImmutableEffectToSlotMap({tap.key: frozenset()})),
                effects=frozenset({tap}),
            ),
        ),
        action_subdefs=(
            SubAbilityDefinition(
                action_node=EffectActionNode(ImmutableEffectToSlotMap({add.key: frozenset()})),
                effects=frozenset({add}),
            ),
        ),
    )


def basic_land_abilities(card, state):
    """!
    @brief Derive intrinsic mana abilities from a land's current basic land subtypes.

    The result is based on current characteristics rather than printed card
    data, so continuous effects that add or remove basic land types also add or
    remove the corresponding intrinsic mana abilities.

    @param card Card whose current land types should be examined.
    @param state Current game state.
    @return Mapping from generated ability keys to intrinsic ability definitions.
    """
    if CardType.LAND not in card.get_types(state):
        return {}

    result = {}

    for subtype in card.get_subtypes(state):
        name = getattr(subtype, "name", str(subtype)).upper()

        if name in BASIC_LAND_MANA:
            definition = mana_ability(BASIC_LAND_MANA[name])
            result[definition.key] = definition

    return result


def basic_land(name):
    """!
    @brief Create a basic land card definition.

    Supports Plains, Island, Swamp, Mountain, Forest, and Wastes. The five typed
    basic lands receive their mana abilities intrinsically from their subtype;
    Wastes has no basic land subtype and therefore stores its colorless mana
    ability explicitly.

    @param name Basic land name.
    @return Corresponding `CardDefinition`.
    @throws ValueError If the requested basic land name is unknown.
    """
    from game.game_state.card import CardDefinition

    key = name.upper()

    if key == "WASTES":
        return CardDefinition(
            "Wastes",
            mana_cost=None,
            types=frozenset({CardType.LAND}),
            abilities=frozenset({mana_ability(ManaType.COLORLESS)}),
        )

    if key not in BASIC_LAND_MANA:
        raise ValueError("Unknown basic land name.")

    return CardDefinition(
        name.title(),
        mana_cost=None,
        types=frozenset({CardType.LAND}),
        subtypes=frozenset({getattr(CardSubtype, key)}),
    )
