"""Deterministic mana-payment planner for the simplified game engine."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Iterable

from .mana_value import ManaRequirement, ManaRequirementFragment, ManaValue
from ..enums import ManaType


@dataclass(frozen=True)
class ManaSource:
    """!
    @brief Declarative description of one available mana-producing ability.

    @var source
        Runtime object providing the mana ability. `None` is reserved for
        already-floating mana in the pool.
    @var ability_key
        Key identifying the mana ability on the source.
    @var produces
        Mana generated by one activation.
    @var costs
        Mana cost required to activate the source.
    @var uses_remaining
        Number of times the source may still be used, or `None` if unbounded.
    @var output_per_activation
        Whether the complete produced value forms one indivisible activation
        bundle rather than independent unit outputs.
    """

    source: object
    ability_key: str
    produces: ManaValue
    costs: ManaValue
    uses_remaining: int | None = 1
    output_per_activation: bool = False


@dataclass(frozen=True)
class ManaPlanStep:
    """!
    @brief One selected mana-source usage in a generated payment plan.

    @var source
        Runtime source to activate, or `None` for floating mana.
    @var ability_key
        Mana ability to activate.
    @var produces
        Mana type selected from the source's possible output.
    """

    source: object
    ability_key: str
    produces: ManaType


@dataclass(frozen=True)
class ManaPlan:
    """!
    @brief Complete mana-generation and payment plan.

    @var steps
        Ordered source usages needed to make the payment possible.
    @var payment
        Concrete payment representation when supplied by the planner.
    """

    steps: tuple[ManaPlanStep, ...]
    payment: object = None


class ManaGenerator:
    """!
    @brief Find a legal mana payment using deterministic source preferences.

    The planner prefers already-floating mana, less flexible sources and cheaper
    activations, while recursive backtracking still guarantees that preference
    ordering cannot invalidate an otherwise legal payment.
    """

    def generate(
        self, requirement: ManaRequirement, state, controller, reserved=frozenset(), mana_pool=None
    ) -> ManaPlan | None:
        """!
        @brief Find a payment plan from floating mana and activatable battlefield sources.

        Ordinary one-mana outputs are solved by matching individual requirement
        fragments against source usages. If a source produces an indivisible
        multi-mana bundle, planning is delegated to the bundle planner.

        `mana_pool` is optional so the original source-only API remains valid.
        Floating mana is represented internally as virtual sources with
        `source=None`, so spending it never creates a real activation.

        @param requirement Mana requirement that must be paid.
        @param state Current game state.
        @param controller Player attempting to pay the requirement.
        @param reserved Runtime sources that may not be activated for this payment.
        @param mana_pool Optional mana already floating in the player's pool.
        @return A legal `ManaPlan`, or `None` if no payment can be found.
        """
        # Expand aggregate requirements into unit fragments so the ordinary
        # planner can assign one source usage to each required mana unit.
        fragments = [
            ManaRequirementFragment(fragment.allowed, 1)
            for fragment in requirement.frags
            for _ in range(fragment.amount)
        ]

        if not fragments:
            return ManaPlan(())

        battlefield_sources = [
            source
            for source in state.get_mana_sources(controller)
            if source.source not in reserved
            and state.can_activate(source.source, source.ability_key)
        ]

        # Multi-mana activations cannot be modeled as independent unit source
        # usages without risking partial consumption of one activation.
        if any(
            source.output_per_activation and sum(source.produces.values()) > 1
            for source in battlefield_sources
        ):
            from .bundle_planner import plan_bundles

            return plan_bundles(requirement, battlefield_sources, mana_pool or {})

        pool_sources = []

        if mana_pool:
            from .mana_value import ColoredSymbol

            # Floating mana behaves like a free virtual source with one usable
            # unit per pool entry.
            for mana, amount in mana_pool.items():
                if amount:
                    pool_sources.append(
                        ManaSource(
                            source=None,
                            ability_key="",
                            produces=ManaValue((ColoredSymbol(frozenset({mana})),)),
                            costs=ManaValue(),
                            uses_remaining=amount,
                        )
                    )

        # Floating mana is free to spend and should be preferred to tapping a
        # permanent when both satisfy the same requirement.
        sources = [*pool_sources, *battlefield_sources]

        # Different mana abilities on one permanent share the same activation
        # resource. Pool entries deliberately receive independent virtual groups.
        groups = [
            source.source if source.source is not None else ("pool", index)
            for index, source in enumerate(sources)
        ]

        # Flexibility is measured per shared resource group, because choosing
        # one ability of a permanent consumes access to its alternative abilities.
        flexibility = {}

        for group, source in zip(groups, sources):
            flexibility.setdefault(group, set()).update(
                mana for symbol in source.produces.symbols for mana in symbol.mana
            )

        # Resolve the most restrictive requirements first so scarce colored
        # sources are not spent prematurely on generic/flexible requirements.
        fragments.sort(key=lambda fragment: len(fragment.allowed))

        def options(source: ManaSource, allowed: frozenset[ManaType]) -> list[ManaType]:
            """!
            @brief Return mana types this source can contribute to one fragment.

            @param source Candidate mana source.
            @param allowed Mana types accepted by the requirement fragment.
            @return Deterministically ordered legal output choices.
            """
            result = {
                mana
                for symbol in source.produces.symbols
                for mana in symbol.mana
                if mana in allowed
            }

            if source.produces.generic and ManaType.COLORLESS in allowed:
                result.add(ManaType.COLORLESS)

            return sorted(result, key=lambda value: value.name)

        failed = set()

        def search(index: int, remaining: dict[int, int], steps: list[ManaPlanStep]):
            """!
            @brief Recursively assign source usages to remaining requirement fragments.

            @param index Index of the next fragment to satisfy.
            @param remaining Remaining uses for each concrete source option.
            @param steps Source usages selected so far.
            @return Complete tuple of plan steps, or `None` if this branch fails.
            """
            if index == len(fragments):
                return tuple(steps)

            fingerprint = (
                index,
                tuple(remaining.values()),
                tuple(group_remaining.values()),
            )

            if fingerprint in failed:
                return None

            # Every remaining fragment needs one remaining group usage. If the
            # shared resource capacity is already too small, the branch is dead.
            if sum(group_remaining.values()) < len(fragments) - index:
                return None

            fragment = fragments[index]
            candidates = []

            for source_index, source in enumerate(sources):
                if (
                    remaining[source_index] <= 0
                    or group_remaining[groups[source_index]] <= 0
                ):
                    continue

                for produced in options(source, fragment.allowed):
                    # Prefer floating mana first, then less flexible groups and
                    # cheaper activation costs. Backtracking still explores
                    # alternatives if the preferred choice blocks later payment.
                    candidates.append(
                        (
                            source.source is not None,
                            len(flexibility[groups[source_index]]),
                            source.costs.cmc(),
                            source_index,
                            produced,
                        )
                    )

            for _, _, _, source_index, produced in sorted(
                candidates, key=lambda item: (*item[:-1], item[-1].name)
            ):
                remaining[source_index] -= 1
                group_remaining[groups[source_index]] -= 1

                source = sources[source_index]

                result = search(
                    index + 1,
                    remaining,
                    steps + [ManaPlanStep(source.source, source.ability_key, produced)],
                )

                # Restore mutable search state before trying another branch.
                remaining[source_index] += 1
                group_remaining[groups[source_index]] += 1

                if result is not None:
                    return result

            failed.add(fingerprint)
            return None

        # A source may expose an explicit use count. Generic output is also
        # treated as repeated colorless capacity in the simplified unit planner.
        remaining = {
            index: (
                len(fragments)
                if source.uses_remaining is None
                else max(source.uses_remaining, source.produces.generic)
            )
            for index, source in enumerate(sources)
        }

        # Shared group capacity prevents multiple alternative mana abilities of
        # the same permanent from being consumed independently.
        group_remaining = {}

        for index, group in enumerate(groups):
            group_remaining[group] = max(
                group_remaining.get(group, 0),
                remaining[index],
            )

        result = search(0, remaining, [])

        return None if result is None else ManaPlan(result)