"""Small state changes shared by the playable example and its tests."""

from __future__ import annotations

from ..enums import ZoneType, CardType, CounterType
from ..game_actions.data_structs.game_action import ResolutionContext
from ..game_actions.data_structs.operation import Operation
from ..game_actions.resolution.event_bus import GameEvent
from ..game_state import Card, Player, State


class MoveCardOperation(Operation):
    """!
    @brief Move one card between zones, including battlefield-entry preparation.
    """

    def __init__(self, context: ResolutionContext, card: Card, destination: ZoneType):
        """!
        @brief Create a zone-change operation.

        Entry replacement effects may mutate the `entry_*` fields before
        execution to describe how the card should enter the battlefield.

        @param context Resolution context producing the move.
        @param card Card being moved.
        @param destination Destination zone.
        """
        super().__init__(context)
        self.card = card
        self.destination = destination
        self.entry_controller = None
        self.entry_tapped = False
        self.entry_counters = {}
        self.entry_copy = None
        self.entry_prepared = False
        self._entry_bindings = {}

    def entry_characteristics(self, state):
        """!
        @brief Return projected characteristics for this battlefield entry.

        The projection is cached on the operation so repeated replacement
        checks observe the same prepared entry view.

        @param state Current game state.
        @return Tuple containing the projected entrant and projected state.
        """
        from ..game_state.entry_projection import entry_projection

        cached = getattr(self, "_entry_view", None)
        if cached is None:
            cached = self._entry_view = entry_projection(state, self)
        return cached

    def _move(self, state):
        """!
        @brief Apply the underlying zone-collection move.
        """
        self.card.owner.move_card(self.card, self.destination, state)

    def execute(self, state: State) -> list[GameEvent]:
        """!
        @brief Execute the zone change and apply prepared entry characteristics.

        @param state Current game state.
        @return Events generated by the move.
        """
        origin = self.card.get_zone()

        if origin == self.destination or (self.card.is_token and self.card.token_left_battlefield):
            return []

        # Preserve the previous controller for the emitted zone-change event.
        controller = self.card.get_controller(state)
        self._move(state)

        if self.destination == ZoneType.BATTLEFIELD and self.entry_prepared:
            if self.entry_copy is not None:
                # Copy effects replace printed characteristics for this new
                # battlefield incarnation while preserving the original values
                # for restoration after it leaves.
                copied = Card(self.entry_copy, self.card.owner, self.card.key)
                self.card._entry_copy_restore = (self.card._definition, self.card._stats)
                self.card._definition, self.card._stats = copied.definition, copied.stats
                self.card.state.counters.clear()

                if self.entry_copy.loyalty is not None:
                    self.card.state.counters[CounterType.LOYALTY] = self.entry_copy.loyalty

            self.card.set_controller(self.entry_controller or self.card.owner)
            self.card.is_tapped = self.entry_tapped

            for counter, amount in self.entry_counters.items():
                self.card.state.counters[counter] = (
                    self.card.state.counters.get(counter, 0) + amount
                )

            state.notify_card_changed(self.card)

        if self.destination == ZoneType.STACK:
            # Preserve information needed while the spell remains on the stack.
            self.card.cast_origin = origin
            self.card.cast_stack_revision = self.card.zone_revision

            from ..enums import SAVariableType

            self.card.state.mana_x = self.context.param_ctx.x_variables.get(SAVariableType.X, 0)
            state.notify_card_changed(self.card)

        # For battlefield entries the resulting controller belongs to the event;
        # for other moves use the controller from before the zone change.
        event_controller = (
            self.card.get_controller(state)
            if self.destination == ZoneType.BATTLEFIELD
            else controller
        )

        return [
            GameEvent(
                "card_moved",
                self.card,
                event_controller,
                {
                    "from": origin.name,
                    "to": self.destination.name,
                    "card": self.card,
                    "previous_controller": controller,
                },
            )
        ]


class DamagePlayerOperation(Operation):
    """!
    @brief Deal damage to a player and capture relevant source characteristics.
    """

    def __init__(self, context: ResolutionContext, target: Player, amount: int):
        """!
        @brief Create a player-damage operation.

        Damage-relevant source keywords and the damage controller are captured
        when the operation is created so later execution uses the characteristics
        associated with this damage event.

        @param context Resolution context producing the damage.
        @param target Player receiving damage.
        @param amount Nonnegative damage amount.
        @throws ValueError If `amount` is not a nonnegative integer.
        """
        super().__init__(context)
        self.target = target
        self.amount = amount

        if not isinstance(amount, int) or isinstance(amount, bool) or amount < 0:
            raise ValueError("Damage must be a nonnegative integer.")

        self.combat = False
        self.unpreventable = False

        source = context.source
        current_state = getattr(source, "_game_state", None)

        information = context.source_information(current_state) if current_state else None
        keywords = information.keywords if information is not None else frozenset()
        self.lifelink = "lifelink" in keywords
        self.deathtouch = "deathtouch" in keywords
        self.infect = "infect" in keywords
        self.wither = "wither" in keywords
        self.damage_controller = information.controller if information else context.controller
        self.source_revision = information.zone_revision if information else context.source_revision

    def execute(self, state: State) -> list[GameEvent]:
        """!
        @brief Apply damage to a player.

        Infect converts player damage into poison counters; ordinary damage
        reduces life.

        @param state Current game state.
        @return Damage and possible lifelink events.
        """
        if self.amount == 0:
            return []

        if self.infect:
            self.target.poison_counters += self.amount
        else:
            self.target.health -= self.amount

        return self._events(state)

    def _events(self, state):
        """!
        @brief Build damage events and resolve immediate lifelink when allowed.

        Batched damage may set `_defer_lifelink` so the operation executor can
        aggregate simultaneous lifelink gains before resolving them.

        @param state Current game state.
        @return Events produced by this damage operation.
        """
        events = [
            GameEvent(
                "damage_dealt",
                self.context.source,
                self.context.controller,
                {
                    "target": self.target.name,
                    "target_object": self.target,
                    "amount": self.amount,
                    "combat": self.combat,
                    "life_loss": (
                        self.amount if isinstance(self.target, Player) and not self.infect else 0
                    ),
                    "source_revision": self.source_revision,
                    "target_revision": getattr(self.target, "zone_revision", None),
                },
            )
        ]

        if (
            self.lifelink
            and self.damage_controller is not None
            and not getattr(self, "_defer_lifelink", False)
        ):
            from dataclasses import replace
            from ..game_actions.life_effects import GainLifeOperation
            from ..game_actions.resolution.replacement_effects import ReplacementResolver

            gain = GainLifeOperation(
                replace(self.context, controller=self.damage_controller), self.amount
            )

            # Lifelink gain is still an operation and therefore passes through
            # replacement effects before changing the game state.
            for operation in ReplacementResolver().replace(state, (gain,)):
                events.extend(operation.execute(state))

        return events


class DamageCreatureOperation(DamagePlayerOperation):
    """!
    @brief Deal damage to a creature or planeswalker permanent.
    """

    def execute(self, state):
        """!
        @brief Apply permanent damage according to its current card types.

        Creature damage is marked normally, or converted to -1/-1 counters by
        infect/wither. Planeswalker damage removes loyalty counters.

        @param state Current game state.
        @return Damage and possible lifelink events.
        """
        if self.amount == 0 or self.target.get_zone() != ZoneType.BATTLEFIELD:
            return []

        types = self.target.get_types(state)

        if not types.intersection({CardType.CREATURE, CardType.PLANESWALKER}):
            return []

        if CardType.CREATURE in types:
            if self.infect or self.wither:
                counters = self.target.state.counters
                counters[CounterType.MINUS_ONE] = (
                    counters.get(CounterType.MINUS_ONE, 0) + self.amount
                )
            else:
                self.target.state.damage_marked += self.amount

            if self.deathtouch:
                self.target.state.damage_by_deathtouch = True

        if CardType.PLANESWALKER in types:
            counters = self.target.state.counters
            counters[CounterType.LOYALTY] = max(
                0, counters.get(CounterType.LOYALTY, 0) - self.amount
            )

        state.notify_card_changed(self.target)
        return self._events(state)


class DrawCardOperation(Operation):
    """!
    @brief Draw one card for the resolution controller.
    """

    def execute(self, state):
        """!
        @brief Move the top card of the controller's deck to hand.

        A failed draw does not move a card and instead marks the player for the
        corresponding state-based loss check.

        @param state Current game state.
        @return Draw-related events.
        """
        player = self.context.controller

        if not player.deck:
            player.failed_draw = True
            return [GameEvent("draw_failed", self.context.source, player)]

        card = next(reversed(player.deck.values()))

        # Reuse the standard zone-change operation so draw movement has exactly
        # the same zone-change semantics and event shape as other moves.
        events = MoveCardOperation(self.context, card, ZoneType.HAND).execute(state)
        events.append(GameEvent("card_drawn", card, player, {"card": card}))

        return events


class TapCardOperation(Operation):
    """!
    @brief Tap a card as an executable state change.
    """

    def __init__(self, context: ResolutionContext, card: Card, *, tap_symbol=True):
        """!
        @brief Create a tap operation.

        @param context Resolution context producing the tap.
        @param card Card to tap.
        @param tap_symbol Whether this represents the source's `{T}` symbol
            rather than a general "tap a permanent" effect or cost.
        """
        super().__init__(context)
        self.card = card

        # A written "tap a creature" cost differs from the source's {T} symbol.
        self.tap_symbol = tap_symbol

    def execute(self, state: State) -> list[GameEvent]:
        """!
        @brief Tap the card and emit a tap event.

        @param state Current game state.
        @return Single `card_tapped` event.
        """
        self.card.is_tapped = True
        return [GameEvent("card_tapped", self.card, self.context.controller)]