from __future__ import annotations

class OperationExecutor:
    """!
    @brief Small adapter that executes operation objects.
    """

    def execute(self, state, operation):
        """!
        @brief Execute one operation against the current state.
        @param state Current game state.
        @param operation Operation to execute.
        @return Events generated by the operation.
        """
        return operation.execute(state)
