"""Execute operation batches and capture resulting trigger eligibility."""

from __future__ import annotations

from collections import Counter

from .event_bus import (
    capture_card_information,
    capture_event,
    capture_trigger_roster,
)


def _lki_cards_for_batch(state, operations, before, stats=None):
    cards = {}

    for ability in before:
        source = getattr(ability, "source", None)

        if getattr(source, "zone_revision", None) is not None:
            cards[id(source)] = source

    for operation in operations:
        operation_cards = operation.lki_cards(state)

        if operation_cards is None:
            if stats is not None:
                stats.lki_fallback_by_operation[
                    type(operation).__name__
                ] += 1

            return None

        for card in operation_cards:
            cards[id(card)] = card

    return tuple(cards.values())


class OperationExecutor:
    """!
    @brief Execute atomic operations while preserving event-time trigger eligibility.

    A batch is treated as one simultaneous mutation boundary: trigger rosters
    and last-known card information are captured before execution, operations
    are applied, and all generated events are bound to triggers against the
    same before/after snapshots.
    """
    def __init__(self):
        self.lki_batches = 0
        self.lki_full_batches = 0
        self.lki_selective_batches = 0
        self.lki_cards_captured = 0
        self.lki_zero_card_batches = 0
        self.lki_fallback_by_operation = Counter()

    def execute(self, state, operation):
        """!
        @brief Execute a single operation against the supplied game state.

        Delegates to `execute_batch` so single operations use the same
        trigger-capture semantics as simultaneous batches.

        @param state Current game state.
        @param operation Operation to execute.
        @return Events generated by the operation with trigger eligibility captured.
        """
        return self.execute_batch(state, (operation,))

    def execute_batch(self, state, operations):
        """!
        @brief Execute a simultaneous group of operations.

        Captures trigger eligibility and last-known information before the
        batch, executes all operations, resolves deferred lifelink gains,
        synchronizes runtime indexes/registers, and finally captures triggers
        for every generated event using the shared before/after snapshots.

        @param state Current game state.
        @param operations Iterable of operations treated as one simultaneous batch.
        @return List of generated events with their triggered abilities captured.
        """
        # All events in this batch share the same pre-mutation trigger roster
        # and last-known card information.
        operations = tuple(operations)

        before = capture_trigger_roster(state)

        self.lki_batches += 1

        lki_cards = _lki_cards_for_batch(
            state,
            operations,
            before,
            self,
        )

        if lki_cards is None:
            self.lki_full_batches += 1
        else:
            self.lki_selective_batches += 1
            self.lki_cards_captured += len(lki_cards)

            if not lki_cards:
                self.lki_zero_card_batches += 1

        information = capture_card_information(
            state,
            lki_cards,
        )

        events = []
        lifelink = {}

        from ...operations.card_operations import DamagePlayerOperation

        for operation in operations:
            previous = getattr(operation, "_defer_lifelink", False)
            damage = isinstance(operation, DamagePlayerOperation)

            # Damage inside a simultaneous batch defers lifelink so all damage
            # is applied before the corresponding life gain is processed.
            if damage:
                operation._defer_lifelink = True

            try:
                generated = operation.execute(state) or ()
            finally:
                if damage:
                    operation._defer_lifelink = previous

            events.extend(generated)

            if (
                damage
                and operation.lifelink
                and operation.damage_controller is not None
            ):
                # Aggregate all damage dealt by the same source/controller pair
                # into one later life-gain operation.
                amount = sum(
                    event.payload["amount"]
                    for event in generated
                    if event.key == "damage_dealt"
                )

                key = (
                    operation.context.source,
                    operation.damage_controller,
                )

                context, total = lifelink.get(
                    key,
                    (operation.context, 0),
                )

                lifelink[key] = (
                    context,
                    total + amount,
                )

        if lifelink:
            from dataclasses import replace
            from ..life_effects import GainLifeOperation
            from .replacement_effects import ReplacementResolver

            # Resolve aggregated lifelink only after the whole damage batch has
            # finished, while still allowing replacement effects to modify the gain.
            for (_, player), (context, amount) in lifelink.items():
                gain = GainLifeOperation(
                    replace(context, controller=player),
                    amount,
                )

                for operation in ReplacementResolver().replace(
                    state,
                    (gain,),
                ):
                    events.extend(
                        operation.execute(state)
                    )

        # Keep query/index structures consistent with the final post-batch state
        # before trigger matching observes it.
        if hasattr(state, "synchronise_registers"):
            state.synchronise_registers()

        # A simultaneous departure uses the shared pre-batch characteristics,
        # even when another departing permanent supplied an anthem or keyword.
        for snapshot in information.values():
            if snapshot.card.zone_revision != snapshot.zone_revision:
                snapshot.card._incarnation_history[snapshot.zone_revision] = snapshot

        after = capture_trigger_roster(state)

        # Bind every event to triggers using the same simultaneous-batch
        # before/after snapshots.
        captured_events = [
            capture_event(
                state,
                event,
                before,
                information,
                after,
            )
            for event in events
        ]

        from ..triggers.runtime_triggers import collect_runtime
        from .event_bus import GameEvent

        # State triggers are checked at the same batch boundary even when the
        # operations themselves produced no publishable event.
        check = GameEvent("state_trigger_check")
        triggers = collect_runtime(state, check, states_only=True)

        if triggers:
            captured_events.append(
                GameEvent(
                    "state_trigger_check",
                    triggered_abilities=tuple(triggers),
                )
            )

        return captured_events

    def print_lki_stats(self):
        print("LKI profiling")
        print(f"  batches:          {self.lki_batches}")
        print(f"  selective:        {self.lki_selective_batches}")
        print(f"  full fallback:    {self.lki_full_batches}")
        print(f"  zero-card:        {self.lki_zero_card_batches}")

        if self.lki_selective_batches:
            average = self.lki_cards_captured / self.lki_selective_batches
            print(f"  avg cards/batch:  {average:.2f}")

        print("  fallback by operation:")

        for name, count in self.lki_fallback_by_operation.most_common():
            print(f"    {name}: {count}")
