from __future__ import annotations

from typing import TYPE_CHECKING
from abc import ABC, abstractmethod
from dataclasses import dataclass, field

if TYPE_CHECKING:
    from ...game_state import State
    from .event_bus import GameEvent
    from ..data_structs.operation import Operation
    from .operation_executor import OperationExecutor


class SBAResolver:
    """!
    @brief Repeatedly applies state-based actions until the state is stable.
    """

    def __init__(self, ops_executor: OperationExecutor, rules: list[StateBasedAction] | None = None) -> None:
        """!
        @brief Create a resolver with the configured state-based action rules.
        @param rules Optional list of rules to evaluate.
        """
        self._operation_executor = ops_executor
        self._rules = list(rules) if rules is not None else []

    def resolve(self, state: State) -> list[GameEvent]:
        """!
        @brief Apply matching rules until no rule changes the state.
        @param state Current game state.
        @return Events generated by applied state-based actions.
        """
        events: list[GameEvent] = []
        while True:
            violations: list[SBAViolation] = []


            for rule in self._rules:
                violations.extend(rule.collect(state))

            if not violations:
                return events

            violations.sort(key=lambda v: v.priority)

            for violation in violations:
                for operation in violation.opertaions:
                    events.extend(
                        self._operation_executor.execute(state, operation)
                    )
    
        
@dataclass(frozen=True)
class SBAViolation:

    opertaions: tuple[Operation] = field(default_factory=tuple)
    priority: int = 0


class StateBasedAction(ABC):
    """!
    @brief Base rule for automatic state cleanup and rule enforcement.
    """
    
    @abstractmethod
    def collect(self, state: State) -> list[SBAViolation]:
        ...
