"""Detect and apply state-based actions until the game state stabilizes."""

from __future__ import annotations

from typing import TYPE_CHECKING
from abc import ABC, abstractmethod
from dataclasses import dataclass, field

if TYPE_CHECKING:
    from ...game_state import State
    from .event_bus import GameEvent
    from ..data_structs.operation import Operation
    from .operation_executor import OperationExecutor


class SBAResolver:
    """!
    @brief Repeatedly detect and apply state-based actions until the state stabilizes.

    Each pass collects all current violations before applying any of them.
    Their operations are then ordered by violation priority, passed through
    replacement processing if configured, and executed as one simultaneous batch.
    """

    def __init__(
        self,
        ops_executor: OperationExecutor,
        rules: list[StateBasedAction] | None = None,
        replace_operations=None,
    ) -> None:
        """!
        @brief Create a resolver with the configured state-based action rules.

        @param ops_executor Executor used to apply generated SBA operations.
        @param rules Optional list of state-based action rules to evaluate.
        @param replace_operations Optional replacement-processing callback applied
               before each simultaneous SBA batch executes.
        """
        self._operation_executor = ops_executor
        self._replace_operations = replace_operations
        self._rules = list(rules) if rules is not None else []

    def resolve(self, state: State) -> list[GameEvent]:
        """!
        @brief Apply state-based actions repeatedly until no violations remain.

        @param state Current game state.
        @return Events generated by all applied SBA batches.
        @throws ValueError If repeated SBA processing fails to reach a stable state.
        """
        events: list[GameEvent] = []

        # The hard limit protects against malformed custom rules or replacement
        # effects that continually recreate the same unstable state.
        for _ in range(128):
            violations: list[SBAViolation] = []

            # Collect against one shared state snapshot before mutating anything.
            for rule in self._rules:
                violations.extend(rule.collect(state))

            if not violations:
                return events

            violations.sort(key=lambda v: v.priority)

            operations = [
                operation
                for violation in violations
                for operation in violation.opertaions
            ]

            if self._replace_operations is not None:
                operations = self._replace_operations(
                    state,
                    operations,
                )

            # All violations detected in this pass are applied as one
            # simultaneous operation batch.
            events.extend(
                self._operation_executor.execute_batch(
                    state,
                    operations,
                )
            )

        raise ValueError(
            "State-based actions failed to stabilize; check custom replacement rules."
        )


@dataclass(frozen=True)
class SBAViolation:
    """!
    @brief Concrete state-based action violation discovered by a rule.

    @var opertaions
        Operations required to correct this violation.
    @var priority
        Ordering key used when several violation groups are collected together.
    """

    opertaions: tuple[Operation] = field(default_factory=tuple)
    priority: int = 0


class StateBasedAction(ABC):
    """!
    @brief Base interface for automatic state cleanup and rule enforcement.
    """

    @abstractmethod
    def collect(self, state: State) -> list[SBAViolation]:
        """!
        @brief Detect all violations of this rule in the current state.

        The method should only inspect state and return the operations needed
        to correct it; mutations happen later through the resolver.

        @param state Current game state.
        @return Violations currently produced by this rule.
        """
        ...


class LethalCreaturesRule(StateBasedAction):
    """!
    @brief Move creatures with lethal state to their owner's graveyard.

    Detects zero-or-less toughness, lethal marked damage, and deathtouch
    damage while respecting indestructible where applicable.
    """

    def collect(self, state):
        """!
        @brief Collect battlefield creatures that should die as an SBA.

        @param state Current game state.
        @return One violation for each lethal creature.
        """
        from ...enums import ZoneType, CardType
        from ...operations.card_operations import MoveCardOperation
        from ..data_structs.game_action import ResolutionContext

        from helper.query_system.query import EqQuery
        from ...game_state.registers.card_register import IK_ZONE, IK_TYPE

        candidates = state.query_cards(
            EqQuery(IK_ZONE, ZoneType.BATTLEFIELD) & EqQuery(IK_TYPE, CardType.CREATURE)
        ) if hasattr(state, "query_cards") else ()
        return [
            SBAViolation(
                (
                    MoveCardOperation(
                        ResolutionContext(
                            source=card,
                            controller=card.get_controller(state),
                        ),
                        card,
                        ZoneType.GRAVEYARD,
                    ),
                )
            )
            for card in candidates
            if card.get_toughness(state) is not None
            and (
                # Zero or negative toughness ignores indestructible.
                card.get_toughness(state) <= 0
                or (
                    not card.has_keyword(state, "indestructible")
                    and (
                        card.state.damage_marked >= card.get_toughness(state)
                        or card.state.damage_by_deathtouch
                    )
                )
            )
        ]


class PlayerLossRule(StateBasedAction):
    """!
    @brief Detect players that lose due to life, drawing or poison state.
    """

    def collect(self, state):
        """!
        @brief Collect players currently satisfying a loss condition.

        @param state Current game state.
        @return Violations marking each newly losing player.
        """
        from ..data_structs.operation import Operation
        from ..data_structs.game_action import ResolutionContext
        from .event_bus import GameEvent

        class LosePlayerOperation(Operation):
            """!
            @brief Operation that records a player's game loss.
            """

            def __init__(self, player, reason):
                super().__init__(
                    ResolutionContext(controller=player)
                )
                self.player = player
                self.reason = reason

            def execute(self, state):
                """!
                @brief Mark the player as lost and emit the corresponding event.

                @param state Current game state.
                @return A single `player_lost` event.
                """
                self.player.has_lost = True
                self.player.loss_reason = self.reason

                if hasattr(state, "player_register"):
                    state.player_register.mark_changed(self.player)

                return [
                    GameEvent(
                        "player_lost",
                        None,
                        self.player,
                        {"reason": self.reason},
                    )
                ]

        violations = []

        from helper.query_system.query import EqQuery, RangeQuery
        from ...game_state.registers.player_register import IK_HAS_LOST, IK_HEALTH, IK_FAILED_DRAW, IK_POISON
        candidates = state.query_players(
            EqQuery(IK_HAS_LOST, False) & (
                RangeQuery(IK_HEALTH, max_value=0) | EqQuery(IK_FAILED_DRAW, True)
                | RangeQuery(IK_POISON, min_value=10)
            )
        ) if hasattr(state, "query_players") else getattr(state, "players", ())
        for player in candidates:
            if getattr(player, "has_lost", False):
                continue

            reason = (
                "life"
                if player.health <= 0
                else (
                    "empty_library"
                    if getattr(player, "failed_draw", False)
                    else (
                        "poison"
                        if getattr(player, "poison_counters", 0) >= 10
                        else None
                    )
                )
            )

            if reason is not None:
                violations.append(
                    SBAViolation(
                        (
                            LosePlayerOperation(
                                player,
                                reason,
                            ),
                        )
                    )
                )

        return violations