from __future__ import annotations

from dataclasses import dataclass, replace, field
from abc import abstractmethod, ABC
from typing import TYPE_CHECKING
from collections.abc import Generator
from ...operations import (
    ConcedeOperation,
    DeclareAttackerOperation,
    DeclareBlockerOperation,
    MuliganOperation,
    PassPriorityOperation,
    RemoveAttackerOperation,
    RemoveBlockerOperation,
)

if TYPE_CHECKING:
    from ...game_state import Card, State, Player
    from ...operations import Operation
    from ...target import TargetBinding
    from ...target.target_resolver import TargetBinding, FrozenTargetBinding
    from .ability import EffectSequence, AbilityDefinition, SubAbilityDefinition
    from ...ai.mana_solver import ManaSolverResult
    from ....helper.runtime_object import RuntimeObject

from ...abilities.parameter_context import ParameterContext

__all__ = [
    "ResolutionContext",
    "ExecutionPlan",
    "FixedExecutionPlan",
    "AbilityExecutionPlan",
    "ScheduledResolution",
    "GameAction",
    "AbilityAction",
    "PassPriorityAction",
    "ConcedeAction",
    "DeclareAttackerAction",
    "RemoveAttackerAction",
    "DeclareBlockerAction",
    "RemoveBlockerAction",
    "MuliganAction",
]


@dataclass(frozen=True)
class ResolutionContext:
    """!
    @brief Information shared with operations while a game action is resolving.
    """

    controller: Player
    source: Card
    ability: AbilityDefinition
    subability: SubAbilityDefinition
    action_key: str
    uses_stack: bool = False
    targets: FrozenTargetBinding | None = None
    effects: EffectSequence | None = None
    param_ctx: ParameterContext = field(default_factory=ParameterContext)


class ExecutionPlan(ABC):
    """!
    @brief Base object that turns an action intent into executable operations.
    """

    @abstractmethod
    def to_operations(self, state: State, context: ResolutionContext) -> Generator[Operation, None, None]:
        """!
        @brief Create operations for the current state and resolution context.
        @param state Current game state.
        @param context Resolution metadata for the action.
        @return Operations that should be executed for this generator.
        """
        ...


@dataclass(frozen=True)
class FixedExecutionPlan(ExecutionPlan):
    """!
    @brief Operation generator that always returns the same operations.
    """

    operations: list[Operation]

    def to_operations(self, state: State, context: ResolutionContext) -> Generator[Operation, None, None]:
        """!
        @brief Return the fixed operation list as an immutable tuple.
        @param state Current game state.
        @param context Resolution metadata for the action.
        @return Fixed operations stored by this generator.
        """
        for o in self.operations:
            yield o
    

@dataclass(frozen=True)
class AbilityExecutionPlan(ExecutionPlan):
    """!
    @brief Creates operations from resolved effect bindings and target choices.
    """

    effects: EffectSequence
    binding: FrozenTargetBinding
    param_context: ParameterContext | None = None
    mana_solver_result: ManaSolverResult | None = None

    def to_operations(self, state: State, context: ResolutionContext) -> Generator[Operation, None, None]:
        """!
        @brief Generate operations for each effect with only its relevant targets.
        @param state Current game state.
        @param context Base resolution metadata for the action.
        @return Operations generated by all bound effects.
        """
        if self.mana_solver_result:
            for mana_action in self.mana_solver_result.mana_plan:
                for intent in mana_action.get_intents():
                    yield from intent.generate_operations(state)

        for eb in self.effects.sequence:
            targets = self._scope_binding(eb.slots)
            n_context = replace(context, targets=targets)
            
            yield from eb.effect.to_operations(state, n_context)

    def _scope_binding(self, slots: frozenset[str]) -> TargetBinding:
        """!
        @brief Keep only the target slots needed by one effect.
        @param slots Slot keys required by one effect.
        @return Target binding limited to those slots.
        """
        return {k: self.binding.get(k) for k in slots}


@dataclass(frozen=True)
class ScheduledResolution:
    """!
    @brief A single resolvable part of a game action with its context.
    """

    generator: ExecutionPlan
    context: ResolutionContext

    def generate_operations(self, state: State) -> Generator[Operation, None, None]:
        """!
        @brief Ask the generator to materialize the operations for this intent.
        @param state Current game state.
        @return Operations to execute for this intent.
        """
        yield from self.generator.to_operations(state, self.context)

    def to_stack_item(self) -> StackItem:
        raise NotImplementedError()


@dataclass(frozen=True)
class StackItem(RuntimeObject):

    action_resolution: ScheduledResolution


class GameAction(ABC):
    """!
    @brief Base command chosen by a player or generated by game rules.
    """

    @abstractmethod
    def get_intents(self) -> tuple[ScheduledResolution, ...]:
        """!
        @brief Split the action into one or more intents that can be executed.
        @return Ordered intents produced by this action.
        """
        ...


@dataclass(frozen=True)
class AbilityAction(GameAction):
    """!
    @brief Game action produced by activating or casting an ability.
    """

    action_key: str
    source: Card
    action_generator: ExecutionPlan
    cost_generator: ExecutionPlan
    uses_stack: bool = True

    def get_intents(self):
        """!
        @brief Return separate intents for paying the cost and resolving the effect.
        @return Cost intent followed by ability effect intent.
        """
        cost_context = ResolutionContext(
            controller=self.source.owner,
            source=self.source,
            ability=None, # TODO
            action_key=self.action_key,
        )

        context = replace(cost_context, uses_stack=self.uses_stack)

        return (
            ScheduledResolution(
                generator=self.cost_generator,
                context=cost_context
            ),
            ScheduledResolution(
                generator=self.action_generator,
                context=context
            )
        )


@dataclass(frozen=True)
class ManaAbilityAction(AbilityAction):

    uses_stack = False


@dataclass(frozen=True)
class PassPriorityAction(GameAction):
    """!
    @brief Action representing a player passing priority.
    """

    player: Player
    
    def get_intents(self):
        """!
        @brief Create the intent that records the priority pass.
        @return Intent for the priority pass operation.
        """
        context=ResolutionContext(
            controller=self.player
        )

        return tuple(
            ScheduledResolution(
                generator=FixedExecutionPlan([PassPriorityOperation(context)]),
                context=context
            )
        )
        
    
@dataclass(frozen=True)
class ConcedeAction(GameAction):
    """!
    @brief Action representing a player conceding the game.
    """

    player: Player

    def get_intents(self) -> list[ScheduledResolution]:
        """!
        @brief Create the intent that resolves the concession.
        @return Intent for the concession operation.
        """
        context=ResolutionContext(
            controller=self.player
        )

        return tuple(
            ScheduledResolution(
                generator=FixedExecutionPlan([ConcedeOperation(context)]),
                context=context
            )
        )
    

@dataclass(frozen=True)
class DeclareAttackerAction(GameAction):
    """!
    @brief Action used to mark a creature as an attacker.
    """

    attacker: Card
    
    def get_intents(self):
        """!
        @brief Create the intent that declares the attacker.
        @return Intent for the attacker declaration operation.
        """
        context=ResolutionContext(
            controller=self.attacker.owner,
            source=self.attacker
        )

        return tuple(
            ScheduledResolution(
                generator=FixedExecutionPlan([DeclareAttackerOperation(context)]),
                context=context
            )
        )


@dataclass(frozen=True)
class RemoveAttackerAction(GameAction):
    """!
    @brief Action used to remove a creature from attacking.
    """

    attacker: Card

    def get_intents(self):
        """!
        @brief Create the intent that removes the attacker declaration.
        @return Intent for the attacker removal operation.
        """
        context=ResolutionContext(
            controller=self.attacker.owner,
            source=self.attacker
        )

        return tuple(
            ScheduledResolution(
                generator=FixedExecutionPlan([RemoveAttackerOperation(context)]),
                context=context
            )
        )


@dataclass(frozen=True)
class DeclareBlockerAction(GameAction):
    """!
    @brief Action used to mark a creature as a blocker.
    """

    blocker: Card

    def get_intents(self):
        """!
        @brief Create the intent that declares the blocker.
        @return Intent for the blocker declaration operation.
        """
        context=ResolutionContext(
            controller=self.blocker.owner,
            source=self.blocker
        )

        return tuple(
            ScheduledResolution(
                generator=FixedExecutionPlan([DeclareBlockerOperation(context)]),
                context=context
            )
        )


@dataclass(frozen=True)
class RemoveBlockerAction(GameAction):
    """!
    @brief Action used to remove a creature from blocking.
    """

    blocker: Card

    def get_intents(self):
        """!
        @brief Create the intent that removes the blocker declaration.
        @return Intent for the blocker removal operation.
        """
        context=ResolutionContext(
            controller=self.blocker.owner,
            source=self.blocker
        )

        return tuple(
            ScheduledResolution(
                generator=FixedExecutionPlan([RemoveBlockerOperation(context)]),
                context=context
            )
        )


@dataclass(frozen=True)
class MuliganAction(GameAction):
    """!
    @brief Action representing a player taking a mulligan.
    """

    player: Player

    def get_intents(self):
        """!
        @brief Create the intent that resolves the mulligan.
        @return Intent for the mulligan operation.
        """
        context = ResolutionContext(controller=self.player)
        return tuple(
            ScheduledResolution(
                generator=FixedExecutionPlan([MuliganOperation(context)]),
                context=context
            )
        )
