"""Atomic operation contracts and basic player action operations."""

from __future__ import annotations

from abc import abstractmethod, ABC
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ...game_state import State
    from .game_action import ResolutionContext
    from ..resolution.event_bus import GameEvent


class Operation(ABC):
    """!
    @brief Base executable state change produced by an action intent.
    """

    def __init__(self, context: ResolutionContext) -> None:
        """!
        @brief Store the resolution context used by this operation.
        @param context Context shared with the operation during execution.
        """
        self.context = context

    @abstractmethod
    def execute(self, state: State) -> list[GameEvent]:
        """!
        @brief Apply this operation to the game state.
        @param state Current game state.
        @return Events generated by the operation.
        """
        pass


class GameEventOperation(Operation):
    """!
    @brief Operation that emits a single game event without changing state.
    """

    event_key: str

    def execute(self, state: State) -> list[GameEvent]:
        """!
        @brief Emit this operation's configured event.
        @param state Current game state.
        @return One game event describing the operation.
        """
        from ..resolution.event_bus import GameEvent

        return [
            GameEvent(
                key=self.event_key,
                source=self.context.source,
                controller=self.context.controller,
            )
        ]


class PassPriorityOperation(GameEventOperation):
    """!
    @brief Operation emitted when a player passes priority.
    """

    event_key = "priority_passed"


class ConcedeOperation(GameEventOperation):
    """!
    @brief Operation emitted when a player concedes.
    """

    event_key = "player_conceded"

    def execute(self, state: State) -> list[GameEvent]:
        """!
        @brief Apply this executable object to the supplied game state.
        """
        self.context.controller.health = 0
        return super().execute(state)
