from __future__ import annotations

from dataclasses import dataclass
from typing import TYPE_CHECKING
from .event_bus import GameEvent, TriggerResolver
from .sba_resolver import SBAResolver
if TYPE_CHECKING:
    from ..game_state import State, CreatureCard
    from ..operations import OperationExecutor, Operation
    from .game_action import ActionIntent
    from .event_bus import EventBus


@dataclass(frozen=True)
class ValidationResult:
    """!
    @brief Describes why an action intent cannot be executed.
    """

    message: str

@dataclass(frozen=True)
class ExecutionResult:
    """!
    @brief Result returned after trying to execute an action intent.
    """

    success: bool
    error: ValidationResult | None
    generated_events: list[GameEvent] | None


class ActionExecutor:
    """!
    @brief Executes action intents, emits events, and resolves follow-up rules.
    """

    def __init__(self, operation_executor: OperationExecutor, event_bus: EventBus) -> None:
        """!
        @brief Create an executor with operation and event handling services.
        @param operation_executor Object that executes individual operations.
        @param event_bus Event bus used to emit and collect events.
        """
        self.operation_executor = operation_executor
        self.event_bus = event_bus
        self.sba_resolver = SBAResolver()
        self.trigger_resolver = TriggerResolver()
    
    def execute(self, state: State, action: ActionIntent) -> ExecutionResult:
        """!
        @brief Validate and execute an action intent.
        @param state Current game state.
        @param action Action intent to execute.
        @return Execution result with generated events or validation error.
        """
        validation_error = self._validate(state, action)

        if validation_error is not None:
            return ExecutionResult(
                success=False,
                error=validation_error,
                generated_events=None
            )

        operations = action.generate_operations(state)
        operations = self._apply_replacement_effects(state, operations)

        events = self._execute_operations(state, operations)

        sba_events = self.sba_resolver.resolve(state)
        events.extend(sba_events)

        self._emit_events(state, events)

        self._resolve_triggers(state, events)

        return ExecutionResult(
            success=True,
            error=None,
            generated_events=events
        )


    def _execute_operations(self, state: State, operations: list[Operation]) -> list[GameEvent]:
        """!
        @brief Execute operations in order and collect their emitted events.
        @param state Current game state.
        @param operations Operations to execute.
        @return Events generated by the operations.
        """
        res: list[GameEvent] = []
        for o in operations:
            res.extend(self.operation_executor.execute(state, o))
        return res
    
    def _validate(self, state: State, action: ActionIntent) -> ValidationResult | None:
        """!
        @brief Validate whether an action intent may currently resolve.
        @param state Current game state.
        @param action Action intent being validated.
        @return Validation error, or None when the action is valid.
        """
        return None
    
    def _apply_replacement_effects(self, state: State, operations: list[Operation]) -> list[Operation]:
        """!
        @brief Apply replacement effects to operations before execution.
        @param state Current game state.
        @param operations Operations that may be replaced.
        @return Operations after replacement effects are applied.
        """
        return operations
    
    def _emit_events(self, state: State, events: list[GameEvent]) -> None:
        """!
        @brief Emit every generated event through the event bus.
        @param state Current game state.
        @param events Events to emit.
        """
        for e in events: self.event_bus.emit(e, state)

    
    def _destroy_creature(self, state: State, creature: CreatureCard) -> None:
        """!
        @brief Move a destroyed creature from battlefield to graveyard.
        @param state Current game state.
        @param creature Creature being destroyed.
        """
        owner = creature.owner
        if creature in owner.battlefield.permanents:
            owner.battlefield.permanents.remove(creature)

        owner.graveyard.append(creature)

        self.event_bus.emit(
            GameEvent(
                key="creature_died",
                source=creature
            ),
            state
        )

    def _resolve_triggers(self, state: State, events: list[GameEvent]) -> None:
        """!
        @brief Collect and resolve triggers caused by generated events.
        @param state Current game state.
        @param events Events that may trigger abilities.
        """
        triggers = self.event_bus.collect_triggered_abilities(state, events)
        self.trigger_resolver.resolve(state, triggers)
    

