from __future__ import annotations

from dataclasses import dataclass, replace
from abc import abstractmethod, ABC
from typing import TYPE_CHECKING
from ..operations import (
    ConcedeOperation,
    DeclareAttackerOperation,
    DeclareBlockerOperation,
    MuliganOperation,
    PassPriorityOperation,
    RemoveAttackerOperation,
    RemoveBlockerOperation,
)

if TYPE_CHECKING:
    from ..game_state import Card, State, Player
    from ..operations import Operation
    from ..target import TargetBinding
    from ..abilities.ability import EffectSequence

__all__ = [
    "ResolutionContext",
    "OperationGenerator",
    "FixedOperationGenerator",
    "AbilityOperationGenerator",
    "ActionIntent",
    "GameAction",
    "AbilityAction",
    "PassPriorityAction",
    "ConcedeAction",
    "DeclareAttackerAction",
    "RemoveAttackerAction",
    "DeclareBlockerAction",
    "RemoveBlockerAction",
    "MuliganAction",
]


@dataclass(frozen=True)
class ResolutionContext:
    """!
    @brief Information shared with operations while a game action is resolving.
    """

    controller: Player | None = None
    source: Card | None = None
    action_key: str | None = None
    uses_stack: bool = False
    targets: TargetBinding | None = None


class OperationGenerator(ABC):
    """!
    @brief Base object that turns an action intent into executable operations.
    """

    @abstractmethod
    def to_operations(self, state: State, context: ResolutionContext) -> tuple[Operation,...]:
        """!
        @brief Create operations for the current state and resolution context.
        @param state Current game state.
        @param context Resolution metadata for the action.
        @return Operations that should be executed for this generator.
        """
        pass


@dataclass(frozen=True)
class FixedOperationGenerator(OperationGenerator):
    """!
    @brief Operation generator that always returns the same operations.
    """

    operations: list[Operation]

    def to_operations(self, state: State, context: ResolutionContext) -> tuple[Operation,...]:
        """!
        @brief Return the fixed operation list as an immutable tuple.
        @param state Current game state.
        @param context Resolution metadata for the action.
        @return Fixed operations stored by this generator.
        """
        return tuple(self.operations)
    

@dataclass(frozen=True)
class AbilityOperationGenerator(OperationGenerator):
    """!
    @brief Creates operations from resolved effect bindings and target choices.
    """

    effects: EffectSequence
    binding: TargetBinding

    def to_operations(self, state: State, context: ResolutionContext) -> tuple[Operation,...]:
        """!
        @brief Generate operations for each effect with only its relevant targets.
        @param state Current game state.
        @param context Base resolution metadata for the action.
        @return Operations generated by all bound effects.
        """
        operations: list[Operation] = [] 

        for e in self.effects:
            targets = self._scope_binding(e.slots)
            n_context = replace(context, targets=targets)
            
            operations.extend(e.effect.to_operations(state, n_context))
        
        return tuple(operations)

    
    def _scope_binding(self, slots: set[str]) -> TargetBinding:
        """!
        @brief Keep only the target slots needed by one effect.
        @param slots Slot keys required by one effect.
        @return Target binding limited to those slots.
        """
        return {k: self.binding.get(k) for k in slots}

    

@dataclass(frozen=True)
class ActionIntent:
    """!
    @brief A single resolvable part of a game action with its context.
    """

    generator: OperationGenerator
    context: ResolutionContext

    def generate_operations(self, state: State) -> tuple[Operation, ...]:
        """!
        @brief Ask the generator to materialize the operations for this intent.
        @param state Current game state.
        @return Operations to execute for this intent.
        """
        return self.generator.to_operations(state, self.context)


class GameAction(ABC):
    """!
    @brief Base command chosen by a player or generated by game rules.
    """

    @abstractmethod
    def get_intents(self) -> list[ActionIntent]:
        """!
        @brief Split the action into one or more intents that can be executed.
        @return Ordered intents produced by this action.
        """
        pass


@dataclass(frozen=True)
class AbilityAction(GameAction):
    """!
    @brief Game action produced by activating or casting an ability.
    """

    action_key: str
    source: Card
    action_generator: OperationGenerator
    cost_generator: OperationGenerator
    uses_stack: bool

    def get_intents(self) -> list[ActionIntent]:
        """!
        @brief Return separate intents for paying the cost and resolving the effect.
        @return Cost intent followed by ability effect intent.
        """
        cost_context = ResolutionContext(
            controller=self.source.owner,
            source=self.source,
            action_key=self.action_key,
        )

        context = replace(cost_context, uses_stack=self.uses_stack)

        return [
            ActionIntent(
                generator=self.cost_generator,
                context=cost_context
            ),
            ActionIntent(
                generator=self.action_generator,
                context=context
            )
        ]


@dataclass(frozen=True)
class PassPriorityAction(GameAction):
    """!
    @brief Action representing a player passing priority.
    """

    player: Player
    
    def get_intents(self) -> list[ActionIntent]:
        """!
        @brief Create the intent that records the priority pass.
        @return Intent for the priority pass operation.
        """
        context=ResolutionContext(
            controller=self.player
        )

        return [
            ActionIntent(
                generator=FixedOperationGenerator([PassPriorityOperation(context)]),
                context=context
            )
        ]
        
    
@dataclass(frozen=True)
class ConcedeAction(GameAction):
    """!
    @brief Action representing a player conceding the game.
    """

    player: Player

    def get_intents(self) -> list[ActionIntent]:
        """!
        @brief Create the intent that resolves the concession.
        @return Intent for the concession operation.
        """
        context=ResolutionContext(
            controller=self.player
        )

        return [
            ActionIntent(
                generator=FixedOperationGenerator([ConcedeOperation(context)]),
                context=context
            )
        ]
    

@dataclass(frozen=True)
class DeclareAttackerAction(GameAction):
    """!
    @brief Action used to mark a creature as an attacker.
    """

    attacker: Card
    
    def get_intents(self) -> list[ActionIntent]:
        """!
        @brief Create the intent that declares the attacker.
        @return Intent for the attacker declaration operation.
        """
        context=ResolutionContext(
            controller=self.attacker.owner,
            source=self.attacker
        )

        return [
            ActionIntent(
                generator=FixedOperationGenerator([DeclareAttackerOperation(context)]),
                context=context
            )
        ]


@dataclass(frozen=True)
class RemoveAttackerAction(GameAction):
    """!
    @brief Action used to remove a creature from attacking.
    """

    attacker: Card

    def get_intents(self) -> list[ActionIntent]:
        """!
        @brief Create the intent that removes the attacker declaration.
        @return Intent for the attacker removal operation.
        """
        context=ResolutionContext(
            controller=self.attacker.owner,
            source=self.attacker
        )

        return [
            ActionIntent(
                generator=FixedOperationGenerator([RemoveAttackerOperation(context)]),
                context=context
            )
        ]


@dataclass(frozen=True)
class DeclareBlockerAction(GameAction):
    """!
    @brief Action used to mark a creature as a blocker.
    """

    blocker: Card

    def get_intents(self) -> list[ActionIntent]:
        """!
        @brief Create the intent that declares the blocker.
        @return Intent for the blocker declaration operation.
        """
        context=ResolutionContext(
            controller=self.blocker.owner,
            source=self.blocker
        )

        return [
            ActionIntent(
                generator=FixedOperationGenerator([DeclareBlockerOperation(context)]),
                context=context
            )
        ]


@dataclass(frozen=True)
class RemoveBlockerAction(GameAction):
    """!
    @brief Action used to remove a creature from blocking.
    """

    blocker: Card

    def get_intents(self) -> list[ActionIntent]:
        """!
        @brief Create the intent that removes the blocker declaration.
        @return Intent for the blocker removal operation.
        """
        context=ResolutionContext(
            controller=self.blocker.owner,
            source=self.blocker
        )

        return [
            ActionIntent(
                generator=FixedOperationGenerator([RemoveBlockerOperation(context)]),
                context=context
            )
        ]


@dataclass(frozen=True)
class MuliganAction(GameAction):
    """!
    @brief Action representing a player taking a mulligan.
    """

    player: Player

    def get_intents(self) -> list[ActionIntent]:
        """!
        @brief Create the intent that resolves the mulligan.
        @return Intent for the mulligan operation.
        """
        context = ResolutionContext(controller=self.player)
        return [
            ActionIntent(
                generator=FixedOperationGenerator([MuliganOperation(context)]),
                context=context
            )
        ]
