from __future__ import annotations

from typing import TYPE_CHECKING
from abc import abstractmethod

if TYPE_CHECKING:
    from ..game_state import State
    from .event_bus import GameEvent


class SBAResolver:
    """!
    @brief Repeatedly applies state-based actions until the state is stable.
    """

    def __init__(self, rules: list[StateBasedAction] | None = None) -> None:
        """!
        @brief Create a resolver with the configured state-based action rules.
        @param rules Optional list of rules to evaluate.
        """
        self.rules = list(rules) if rules is not None else []

    def resolve(self, state: State) -> list[GameEvent]:
        """!
        @brief Apply matching rules until no rule changes the state.
        @param state Current game state.
        @return Events generated by applied state-based actions.
        """
        events: list[GameEvent] = []
        is_changed = True
        while is_changed:
            is_changed = False

            for rule in self.rules:
                if not rule.applies(state):
                    continue

                events.extend(rule.execute(state))
                is_changed = True
        
        return events
    
        


class StateBasedAction:
    """!
    @brief Base rule for automatic state cleanup and rule enforcement.
    """
    
    @abstractmethod
    def applies(self, state: State) -> bool:
        """!
        @brief Check whether this state-based action should run.
        @param state Current game state.
        @return True if the rule applies.
        """
        pass

    @abstractmethod
    def execute(self, state: State) -> list[GameEvent]:
        """!
        @brief Apply the state-based action.
        @param state Current game state.
        @return Events generated by the action.
        """
        pass
